name: Deploy

on:
  [workflow_dispatch]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Key
        run: |
          set -eu
          mkdir "$HOME/.ssh"
          echo "${{ secrets.key }}" > "$HOME/.ssh/key"
          chmod 600 "$HOME/.ssh/key"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Node Setup
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Node Install
        run: npm install

      - name: Build
        run: npm run docs:build

      - name: Upload
        run: |
          rsync -e "ssh -p ${{ secrets.port }} -i $HOME/.ssh/key -o StrictHostKeyChecking=no" --archive --compress --delete ./.vitepress/dist ${{ secrets.user }}@${{ secrets.host }}:${{ secrets.path }}/web

      - name: Scripts
        run: |
          ssh -p ${{ secrets.port }} -i $HOME/.ssh/key -o StrictHostKeyChecking=no ${{ secrets.user }}@${{ secrets.host }} '${{ secrets.path }}/.deploy/scripts.sh'
