name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup key
        run: |
          set -eu
          mkdir "$HOME/.ssh"
          echo "${{ secrets.key }}" > "$HOME/.ssh/key"
          chmod 600 "$HOME/.ssh/key"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run docs:build

      - name: Upload artifact
        run: |
          rsync -e "ssh -p ${{ secrets.port }} -i $HOME/.ssh/key -o StrictHostKeyChecking=no" --archive --compress --delete ./.vitepress/dist ${{ secrets.user }}@${{ secrets.host }}:${{ secrets.path }}/web

      - name: Run scripts
        run: |
          ssh -p ${{ secrets.port }} -i $HOME/.ssh/key -o StrictHostKeyChecking=no ${{ secrets.user }}@${{ secrets.host }} '${{ secrets.path }}/.deploy/scripts.sh'
